markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Luke Underwood
production_url : http://lju.me
description: "I collection of things that I thought about for fun."
disqus_shortname: ellju
analytics: UA-40273599-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : Lucas Jesse Underwood
  github : elju
  twitter : nonintuitive
  email: more.silenter@gmail.com
